DEVELOPMENT: change to push 1) to development, 2) merge to test, 3) push to test

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -1,5 +1,5 @@
 #!/bin/bash
-exit 0 
+exit 0
 # find node
 NODE=$(which node)
  
@@ -16,18 +16,23 @@ if [[ ! -d ~/.npm/jslint ]]; then
 	echo "Please install jslint (global )first."
 	exit 1
 fi
+
+git diff --name-only | egrep '.js$' | while read FILE; do
+	echo "=== $FILE"
+done
+echo DONE
  
 # run JSLint before every commit, don't commit until
 # JSLint is OK
-for file in $(git diff --name-only --cached | egrep '.js$');
+for file in $(git diff --name-only | egrep '.js$');
 do
 	echo "--- $file"
-	$NODE ~/.npm/jslint/bin/jslint.js $file
-	# If the result of the previous command is NOT zero
-	if [ $? -ne 0 ]; then
-	 echo "*** ERROR *** : JSLint failed for file: $file, please fix code and recommit"
-	 exit 1
-	fi
+	#$NODE ~/.npm/jslint/bin/jslint.js $file
+	## If the result of the previous command is NOT zero
+	#if [ $? -ne 0 ]; then
+	# echo "*** ERROR *** : JSLint failed for file: $file, please fix code and recommit"
+	# exit 1
+	#fi
 done
 
 exit 1
